name: CI

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  push:
    branches: [main]

jobs:
  quality-checks:
    name: Quality Checks & Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Generate cache key
        id: cache-key
        run: |
          echo "key=deps-${{ runner.os }}-node-20-${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            deps-${{ runner.os }}-node-20-

      - name: Install dependencies
        run: npm ci

      - name: Cache Prisma
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.prisma
            prisma/generated
          key: prisma-${{ runner.os }}-${{ hashFiles('prisma/schema.prisma') }}
          restore-keys: |
            prisma-${{ runner.os }}-

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm run test:ci

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.sha }}
          path: |
            coverage/**
            vitest-report.*
          retention-days: 7

      # Only build on main branch pushes
      - name: Cache Next.js build
        if: github.ref == 'refs/heads/main'
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            .next/static
            .next/standalone
          key: nextjs-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            nextjs-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-

      - name: Generate OpenAPI documentation
        if: github.ref == 'refs/heads/main'
        run: npx next-openapi-gen generate

      - name: Build for production
        if: github.ref == 'refs/heads/main'
        run: npx opennextjs-cloudflare build
        env:
          NODE_ENV: production

      - name: Upload build artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            .next
            .open-next
            public
            package.json
            package-lock.json
            wrangler.json
            open-next.config.ts
            next.openapi.json
          retention-days: 1
          if-no-files-found: error
